pipeline {
    agent any
    environment {
    PATH = "C:\\WINDOWS\\SYSTEM32"
    }
    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }
    stages {
        stage('Build') {
            steps {
                //sh 'mvn -B -DskipTests clean package'
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                //sh 'mvn test'
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                //sh './jenkins/scripts/deliver.sh'
                bat './jenkins/scripts/deliver.bat'
            }
        }
    }
}
